import type { AnimationState } from '@/entity/components/Animatable';
import * as PIXI from 'pixi.js';
import type { FrameObject, ISpritesheetData, Spritesheet } from 'pixi.js';
import type { Rectangle, Size } from './types';

// Generated by https://quicktype.io

export interface AsepriteSheet {
  frames: FrameElement[];
  meta: Meta;
}

export interface FrameElement {
  filename: string;
  frame: Rectangle;
  rotated: boolean;
  trimmed: boolean;
  spriteSourceSize: Rectangle;
  sourceSize: Size;
  duration: number;
}

export interface Meta {
  app: string;
  version: string;
  image: string;
  format: string;
  size: Size;
  scale: string;
  frameTags: FrameTag[];
  layers: Layer[];
  slices: Slice[];
}

export interface FrameTag {
  name: string;
  from: number;
  to: number;
  direction: string;
}

export interface Layer {
  name: string;
  opacity: number;
  blendMode: string;
}

export interface Slice {
  name: string;
  color: string;
  keys: SliceKey[];
}

export interface SliceKey {
  frame: number;
  bounds: Rectangle;
}

export interface AsepriteSheet {
  frames: FrameElement[];
  meta: Meta;
}

export interface FrameElement {
  filename: string;
  frame: Rectangle;
  rotated: boolean;
  trimmed: boolean;
  spriteSourceSize: Rectangle;
  sourceSize: Size;
  duration: number;
}

export interface Meta {
  app: string;
  version: string;
  image: string;
  format: string;
  size: Size;
  scale: string;
  frameTags: FrameTag[];
}

export interface FrameTag {
  name: string;
  from: number;
  to: number;
  direction: string;
}

export function parseAsperiteAnimationSheet(
  asepritesheet: AsepriteSheet
): ISpritesheetData {
  return {
    frames: Object.fromEntries(
      asepritesheet.frames.map(frame => {
        const frameName = frame.filename;
        // avoids console warnings with HMR
        if (import.meta.env.DEV) {
          PIXI.Texture.removeFromCache(frameName);
        }
        return [frameName, frame];
      })
    ),
    animations: Object.fromEntries(
      asepritesheet.meta.frameTags.map(tag => [
        tag.name,
        asepritesheet.frames
          .slice(tag.from, tag.to + 1)
          .map(frame => frame.filename)
      ])
    ),
    meta: { scale: '1' }
  };
}

export const createSpritesheetFrameObject = (
  name: AnimationState,
  spritesheet: Spritesheet,
  spritesheetData: ISpritesheetData
): FrameObject[] => {
  const frames = spritesheet.animations[name];
  if (!frames) throw new Error(`unknown animation: ${name}`);

  return frames.map((frame, index) => {
    const frameName = spritesheetData.animations?.[name]?.[index];
    return {
      texture: frame,
      // @ts-ignore bruh
      time: spritesheetData.frames[frameName].duration
    };
  });
};
